name: React App build and deployment

on:
  push:
    branches: [ main ]

jobs:
   react-build-deploy:
         runs-on: ubuntu-latest

         steps:
           - name: Checkout
             uses: actions/checkout@v6.0.2
           - name: Setup Node.js environment
             uses: actions/setup-node@v6.1.0
             with: 
                node-version: 23.x
           - name: Install all the dependencies 
             run: npm ci 
           - name: Run the Build command 
             run: npm run predeploy
           - name: Configure Git identity
             run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
           - name: Deploy to GitHub Pages
             run: npm run deploy
             env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
